//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VecherVKomnatu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dogovor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dogovor()
        {
            this.Oplata = new HashSet<Oplata>();
            this.Smeta = new HashSet<Smeta>();
        }
    
        public int id { get; set; }
        public System.DateTime dateSostav { get; set; }
        public int klient { get; set; }
        public System.DateTime dateN { get; set; }
        public System.DateTime dateK { get; set; }
        public int brigada { get; set; }
    
        public virtual Brigada Brigada1 { get; set; }
        public virtual Klient Klient1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oplata> Oplata { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Smeta> Smeta { get; set; }
    }
}
