//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VecherVKomnatu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ВечерВКвартируEntities : DbContext
    {
        public ВечерВКвартируEntities()
            : base("name=ВечерВКвартируEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brigada> Brigada { get; set; }
        public virtual DbSet<Dogovor> Dogovor { get; set; }
        public virtual DbSet<EdIzmer> EdIzmer { get; set; }
        public virtual DbSet<Klient> Klient { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Mat> Mat { get; set; }
        public virtual DbSet<Oplata> Oplata { get; set; }
        public virtual DbSet<Rab> Rab { get; set; }
        public virtual DbSet<Smeta> Smeta { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeUser> TypeUser { get; set; }
        public virtual DbSet<Uslugi> Uslugi { get; set; }
    }
}
