//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VecherVKomnatu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oplata
    {
        public int id { get; set; }
        public System.DateTime dateOplat { get; set; }
        public decimal sum { get; set; }
        public int dogovor { get; set; }
    
        public virtual Dogovor Dogovor1 { get; set; }
    }
}
