//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VecherVKomnatu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rab
    {
        public int id { get; set; }
        public string FIO { get; set; }
        public string tel { get; set; }
        public System.DateTime dateR { get; set; }
        public decimal salary { get; set; }
        public int brigada { get; set; }
        public int seria { get; set; }
        public int nomer { get; set; }
    
        public virtual Brigada Brigada1 { get; set; }
    }
}
