//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VecherVKomnatu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Smeta
    {
        public int id { get; set; }
        public int dog { get; set; }
        public int uslugi { get; set; }
        public int mat { get; set; }
        public int kolMat { get; set; }
    
        public virtual Dogovor Dogovor { get; set; }
        public virtual Mat Mat1 { get; set; }
        public virtual Uslugi Uslugi1 { get; set; }
    }
}
